---
title: "Regression Models for Count Data: beyond the Poisson model"
author:
  - Wagner Hugo Bonat
  - Walmes Marques Zeviani
  - Eduardo Elias Ribeiro Jr
documentclass: book
papersize: a5
fontsize: 9pt
geometry: [left=2cm, right=1.2cm, top=1.5cm, bottom=1.5cm]
bibliography: [config/rmcd.bib]
biblio-style: apalike
---

# Preface {-}

The main goal of this material is to provide a technical support for 
the students attending the course ''Regression models for count data: 
beyond the Poisson model", given as part of the XV Brazilian School of 
Regression models - March/2017 in Goiânia, Brazil. 

The main goal of this course is to present a wider range of statistical 
models to deal with count data. In particular, we focus on parametric 
and second-moments specified models. We shall present the model 
specification along with strategies for model fitting and the 
associated `R` code. Furthermore, this book-course and supplementary 
material as `R` [@R2015] code and data sets are available for the students. 

We intend to keep the course in a level suitable for bachelor students 
who already attended a course on generalized linear models [@Nelder1972]. 
However, since the course also covers updated topics, it can be of 
interest of postgraduate students and researches in general. 

We designed the course for three hours of tuition. 
In the first part (two hours) of the course, we shall present the 
analysis of count data based on fully parametric models.
After a brief introduction and motivation on count data, we present the
Gamma-Count, Poisson-Tweedie and COM-Poisson distributions. We explore
their properties through a consideration of dispersion, 
zero-inflated and heavy tail indexes, and illustrate their applications 
with four data analyses. The estimation of these models based on the 
likelihood paradigm is discussed along with `R` code and worked examples.

In the second part (one hour) of the course, we provide a brief 
introduction to the estimating function approach [@Jorgensen2004 ; @Bonat2016a]
and discuss models based on second-moments assumptions in the style of @Wedderburn1974. 
In particular, we focus on the recently proposed Extended Poisson-Tweedie [@Bonat2016b] 
and the quasi-Poisson models.
The estimating function approach adopted for estimation and inference is presented 
along with `R` code and data examples. The use of the `R` package `mcglm` 
[@Bonat2016c] is discussed for fitting the extended Poisson-Tweedie model.

We acknowledge our gratitude to the scientific committee of XV Brazilian
regression model school for this opportunity.





